-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.admin_activity_feed (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  activity_type text NOT NULL,
  actor_id uuid,
  actor_username text,
  actor_email text,
  target_type text NOT NULL,
  target_id text NOT NULL,
  target_name text,
  action text NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  severity text NOT NULL DEFAULT 'info'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_activity_feed_pkey PRIMARY KEY (id),
  CONSTRAINT admin_activity_feed_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  action_type text NOT NULL,
  admin_id uuid NOT NULL,
  admin_email text NOT NULL,
  target_type text NOT NULL,
  target_id text NOT NULL,
  reason text NOT NULL,
  before_state jsonb,
  after_state jsonb,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES auth.users(id)
);
CREATE TABLE public.admin_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'moderator'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'moderator'::text, 'viewer'::text])),
  permissions jsonb NOT NULL DEFAULT '{"can_ban_users": false, "can_export_data": false, "can_delete_users": false, "can_manage_queue": true, "can_manage_admins": false, "can_moderate_users": true, "can_edit_hackathons": false, "can_view_audit_logs": true, "can_access_analytics": true, "can_delete_hackathons": false, "can_reject_hackathons": true, "can_revoke_organizers": false, "can_approve_hackathons": true, "can_feature_hackathons": false, "can_send_announcements": false, "can_unpublish_hackathons": false}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_roles_pkey PRIMARY KEY (id),
  CONSTRAINT admin_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT admin_roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT admin_roles_user_id_profiles_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.blogs (
  id integer NOT NULL DEFAULT nextval('blogs_id_seq'::regclass),
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  author text NOT NULL,
  cover_image text,
  excerpt text,
  tags jsonb,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  reading_time_minutes integer,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['published'::text, 'draft'::text])),
  CONSTRAINT blogs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.certificate_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  thumbnail_url text,
  is_default boolean DEFAULT false,
  is_public boolean DEFAULT false,
  created_by uuid,
  template_data jsonb NOT NULL,
  canvas_config jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT certificate_templates_pkey PRIMARY KEY (id),
  CONSTRAINT fk_created_by FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  certificate_id text NOT NULL UNIQUE CHECK (certificate_id ~ '^CERT-[A-Z0-9]{6}$'::text),
  participant_name text NOT NULL,
  participant_email text,
  hackathon_name text NOT NULL,
  type USER-DEFINED NOT NULL,
  position text,
  pdf_url text,
  jpg_url text,
  status USER-DEFINED NOT NULL DEFAULT 'active'::certificate_status,
  generated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  admin_email text,
  maximally_username text NOT NULL DEFAULT ''::text,
  template_id uuid,
  batch_id text,
  CONSTRAINT certificates_pkey PRIMARY KEY (id),
  CONSTRAINT fk_template_used FOREIGN KEY (template_id) REFERENCES public.certificate_templates(id),
  CONSTRAINT fk_generated_by FOREIGN KEY (generated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.dashboard (
  id integer NOT NULL DEFAULT 1,
  featured_hackathon_name text,
  featured_hackathon_id integer,
  featured_core_id_1 integer,
  featured_core_id_2 integer,
  featured_core_id_3 integer,
  CONSTRAINT dashboard_pkey PRIMARY KEY (id),
  CONSTRAINT fk_featured_core_1 FOREIGN KEY (featured_core_id_1) REFERENCES public.people(id),
  CONSTRAINT fk_featured_core_2 FOREIGN KEY (featured_core_id_2) REFERENCES public.people(id),
  CONSTRAINT fk_featured_core_3 FOREIGN KEY (featured_core_id_3) REFERENCES public.people(id)
);
CREATE TABLE public.email_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  template_name text,
  recipients ARRAY NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text, 'pending'::text])),
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  sent_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT email_logs_pkey PRIMARY KEY (id),
  CONSTRAINT email_logs_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.email_templates(id),
  CONSTRAINT email_logs_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['judges'::text, 'sponsors'::text, 'participants'::text, 'general'::text, 'custom'::text])),
  subject text NOT NULL,
  body text NOT NULL,
  placeholders jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.featured_hackathons (
  id integer NOT NULL DEFAULT 1,
  slot_1_type text CHECK (slot_1_type = ANY (ARRAY['admin'::text, 'organizer'::text])),
  slot_1_id integer,
  slot_2_type text CHECK (slot_2_type = ANY (ARRAY['admin'::text, 'organizer'::text])),
  slot_2_id integer,
  slot_3_type text CHECK (slot_3_type = ANY (ARRAY['admin'::text, 'organizer'::text])),
  slot_3_id integer,
  slot_4_type text CHECK (slot_4_type = ANY (ARRAY['admin'::text, 'organizer'::text])),
  slot_4_id integer,
  slot_5_type text CHECK (slot_5_type = ANY (ARRAY['admin'::text, 'organizer'::text])),
  slot_5_id integer,
  slot_6_type text CHECK (slot_6_type = ANY (ARRAY['admin'::text, 'organizer'::text])),
  slot_6_id integer,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT featured_hackathons_pkey PRIMARY KEY (id),
  CONSTRAINT featured_hackathons_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.gallery_project_likes (
  id integer NOT NULL DEFAULT nextval('gallery_project_likes_id_seq'::regclass),
  project_id integer NOT NULL,
  user_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_project_likes_pkey PRIMARY KEY (id),
  CONSTRAINT gallery_project_likes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.gallery_projects(id),
  CONSTRAINT gallery_project_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.gallery_projects (
  id integer NOT NULL DEFAULT nextval('gallery_projects_id_seq'::regclass),
  user_id uuid NOT NULL,
  name character varying NOT NULL,
  tagline character varying,
  description text NOT NULL,
  logo_url text,
  cover_image_url text,
  github_url text,
  demo_url text,
  video_url text,
  website_url text,
  category character varying,
  tags ARRAY DEFAULT '{}'::text[],
  technologies ARRAY DEFAULT '{}'::text[],
  readme_content text,
  hackathon_id integer,
  hackathon_submission_id integer,
  hackathon_position character varying,
  status character varying DEFAULT 'pending'::character varying,
  moderation_notes text,
  moderated_by uuid,
  moderated_at timestamp with time zone,
  view_count integer DEFAULT 0,
  like_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gallery_projects_pkey PRIMARY KEY (id),
  CONSTRAINT gallery_projects_moderated_by_fkey FOREIGN KEY (moderated_by) REFERENCES auth.users(id),
  CONSTRAINT gallery_projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT gallery_projects_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  date date NOT NULL DEFAULT CURRENT_DATE,
  page_views integer DEFAULT 0,
  unique_visitors integer DEFAULT 0,
  registration_starts integer DEFAULT 0,
  registration_completions integer DEFAULT 0,
  team_formations integer DEFAULT 0,
  submissions_count integer DEFAULT 0,
  average_session_duration integer DEFAULT 0,
  bounce_rate numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_analytics_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_announcement_reads (
  id integer NOT NULL DEFAULT nextval('hackathon_announcement_reads_id_seq'::regclass),
  announcement_id integer NOT NULL,
  user_id text NOT NULL,
  read_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_announcement_reads_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_announcement_reads_announcement_id_fkey FOREIGN KEY (announcement_id) REFERENCES public.hackathon_announcements(id)
);
CREATE TABLE public.hackathon_announcements (
  id integer NOT NULL DEFAULT nextval('hackathon_announcements_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  title text NOT NULL,
  content text NOT NULL,
  announcement_type text NOT NULL CHECK (announcement_type = ANY (ARRAY['general'::text, 'important'::text, 'reminder'::text, 'update'::text])),
  target_audience text NOT NULL CHECK (target_audience = ANY (ARRAY['all'::text, 'confirmed'::text, 'waitlist'::text, 'teams'::text, 'individuals'::text, 'public'::text])),
  send_email boolean DEFAULT false,
  is_published boolean DEFAULT false,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  published_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_announcements_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_announcements_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_custom_answers (
  id integer NOT NULL DEFAULT nextval('hackathon_custom_answers_id_seq'::regclass),
  registration_id integer NOT NULL,
  question_id integer NOT NULL,
  answer_text text,
  answer_array ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_custom_answers_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_custom_answers_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.hackathon_registrations(id),
  CONSTRAINT hackathon_custom_answers_question_id_fkey FOREIGN KEY (question_id) REFERENCES public.hackathon_custom_questions(id)
);
CREATE TABLE public.hackathon_custom_questions (
  id integer NOT NULL DEFAULT nextval('hackathon_custom_questions_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  question_text text NOT NULL,
  question_type text NOT NULL CHECK (question_type = ANY (ARRAY['text'::text, 'textarea'::text, 'select'::text, 'multiselect'::text, 'checkbox'::text, 'radio'::text])),
  options ARRAY,
  is_required boolean DEFAULT false,
  order_index integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_custom_questions_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_custom_questions_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_edit_requests (
  id integer NOT NULL DEFAULT nextval('hackathon_edit_requests_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  organizer_id text NOT NULL,
  organizer_email text NOT NULL,
  requested_changes jsonb NOT NULL,
  edit_reason text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_at timestamp with time zone,
  reviewed_by text,
  admin_notes text,
  rejection_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_edit_requests_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_edit_requests_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_email_campaigns (
  id integer NOT NULL DEFAULT nextval('hackathon_email_campaigns_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  campaign_name text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  target_filter jsonb,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'sending'::text, 'sent'::text, 'failed'::text])),
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  recipients_count integer DEFAULT 0,
  opened_count integer DEFAULT 0,
  clicked_count integer DEFAULT 0,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_email_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_email_campaigns_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_feedback_forms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  form_title text NOT NULL,
  form_description text,
  form_type text NOT NULL CHECK (form_type = ANY (ARRAY['pre-event'::text, 'mid-event'::text, 'post-event'::text, 'mentor'::text, 'judge'::text, 'sponsor'::text])),
  questions jsonb NOT NULL,
  is_active boolean DEFAULT true,
  is_anonymous boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_feedback_forms_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_feedback_forms_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_feedback_responses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  form_id uuid NOT NULL,
  respondent_id uuid,
  responses jsonb NOT NULL,
  submitted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_feedback_responses_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_feedback_responses_respondent_id_fkey FOREIGN KEY (respondent_id) REFERENCES auth.users(id),
  CONSTRAINT hackathon_feedback_responses_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.hackathon_feedback_forms(id)
);
CREATE TABLE public.hackathon_judges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  role_title text,
  company text,
  bio text CHECK (char_length(bio) <= 200),
  profile_photo text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_judges_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_judges_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_mentors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  mentor_id uuid NOT NULL,
  expertise_areas ARRAY NOT NULL DEFAULT '{}'::text[],
  availability_slots jsonb DEFAULT '[]'::jsonb,
  max_mentees integer DEFAULT 5,
  current_mentees integer DEFAULT 0,
  bio text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'busy'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_mentors_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_mentors_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_mentors_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.hackathon_mentorship_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  mentor_id uuid NOT NULL,
  mentee_id uuid NOT NULL,
  team_id integer,
  session_type text NOT NULL CHECK (session_type = ANY (ARRAY['one-on-one'::text, 'team'::text, 'workshop'::text, 'office-hours'::text])),
  scheduled_at timestamp with time zone,
  duration_minutes integer DEFAULT 30,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'completed'::text, 'cancelled'::text, 'no-show'::text])),
  notes text,
  feedback_rating integer CHECK (feedback_rating >= 1 AND feedback_rating <= 5),
  feedback_text text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_mentorship_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_mentorship_sessions_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id),
  CONSTRAINT hackathon_mentorship_sessions_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_mentorship_sessions_mentor_id_fkey FOREIGN KEY (mentor_id) REFERENCES public.profiles(id),
  CONSTRAINT hackathon_mentorship_sessions_mentee_id_fkey FOREIGN KEY (mentee_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.hackathon_organizers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL DEFAULT 'co-organizer'::text CHECK (role = ANY (ARRAY['owner'::text, 'co-organizer'::text, 'admin'::text, 'viewer'::text])),
  permissions jsonb DEFAULT '{"can_edit": true, "can_manage_judges": false, "can_view_analytics": true, "can_manage_submissions": true, "can_manage_announcements": true, "can_manage_registrations": true}'::jsonb,
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  accepted_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'removed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  invite_token text UNIQUE,
  invite_expires_at timestamp with time zone,
  CONSTRAINT hackathon_organizers_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_organizers_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id),
  CONSTRAINT hackathon_organizers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT hackathon_organizers_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_participant_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  user_id uuid,
  overall_rating integer CHECK (overall_rating >= 1 AND overall_rating <= 5),
  organization_rating integer CHECK (organization_rating >= 1 AND organization_rating <= 5),
  mentorship_rating integer CHECK (mentorship_rating >= 1 AND mentorship_rating <= 5),
  experience_highlights text,
  improvement_suggestions text,
  testimonial text,
  would_recommend boolean DEFAULT true,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_participant_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_participant_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT hackathon_participant_feedback_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_participant_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  sender_id uuid,
  sender_type text NOT NULL CHECK (sender_type = ANY (ARRAY['organizer'::text, 'participant'::text, 'judge'::text, 'mentor'::text])),
  recipient_type text NOT NULL CHECK (recipient_type = ANY (ARRAY['all'::text, 'team'::text, 'individual'::text, 'judges'::text, 'mentors'::text])),
  recipient_ids ARRAY,
  team_id integer,
  subject text NOT NULL,
  message text NOT NULL,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  is_announcement boolean DEFAULT false,
  read_by ARRAY DEFAULT '{}'::uuid[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_participant_messages_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_participant_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT hackathon_participant_messages_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_participant_messages_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id)
);
CREATE TABLE public.hackathon_registration_analytics (
  id integer NOT NULL DEFAULT nextval('hackathon_registration_analytics_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  date date NOT NULL,
  registrations_count integer DEFAULT 0,
  teams_formed_count integer DEFAULT 0,
  waitlist_count integer DEFAULT 0,
  checked_in_count integer DEFAULT 0,
  CONSTRAINT hackathon_registration_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_registration_analytics_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_registration_notes (
  id integer NOT NULL DEFAULT nextval('hackathon_registration_notes_id_seq'::regclass),
  registration_id integer NOT NULL,
  note_text text NOT NULL,
  created_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_registration_notes_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_registration_notes_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.hackathon_registrations(id)
);
CREATE TABLE public.hackathon_registration_tag_assignments (
  id integer NOT NULL DEFAULT nextval('hackathon_registration_tag_assignments_id_seq'::regclass),
  registration_id integer NOT NULL,
  tag_id integer NOT NULL,
  assigned_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_registration_tag_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_registration_tag_assignments_registration_id_fkey FOREIGN KEY (registration_id) REFERENCES public.hackathon_registrations(id),
  CONSTRAINT hackathon_registration_tag_assignments_tag_id_fkey FOREIGN KEY (tag_id) REFERENCES public.hackathon_registration_tags(id)
);
CREATE TABLE public.hackathon_registration_tags (
  id integer NOT NULL DEFAULT nextval('hackathon_registration_tags_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  tag_name text NOT NULL,
  tag_color text DEFAULT '#6B7280'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_registration_tags_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_registration_tags_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_registrations (
  id integer NOT NULL DEFAULT nextval('hackathon_registrations_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  user_id_old text,
  username text NOT NULL,
  email text NOT NULL,
  full_name text NOT NULL,
  registration_type text NOT NULL CHECK (registration_type = ANY (ARRAY['individual'::text, 'team'::text])),
  team_id integer,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'checked_in'::text, 'cancelled'::text, 'waitlist'::text])),
  phone_number text,
  college_university text,
  graduation_year integer,
  github_url text,
  linkedin_url text,
  portfolio_url text,
  skills ARRAY,
  experience_level text CHECK (experience_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text])),
  looking_for_team boolean DEFAULT false,
  preferred_role text,
  dietary_restrictions text,
  tshirt_size text,
  registration_number text UNIQUE,
  checked_in_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  team_role text CHECK (team_role IS NULL OR (team_role = ANY (ARRAY['leader'::text, 'developer'::text, 'designer'::text, 'pm'::text, 'marketing'::text, 'other'::text]))),
  user_id uuid,
  CONSTRAINT hackathon_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_registrations_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_registrations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id),
  CONSTRAINT hackathon_registrations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.hackathon_resources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  title text NOT NULL,
  description text,
  resource_type text NOT NULL CHECK (resource_type = ANY (ARRAY['document'::text, 'video'::text, 'link'::text, 'code'::text, 'dataset'::text, 'api'::text, 'tool'::text])),
  url text NOT NULL,
  category text,
  tags ARRAY DEFAULT '{}'::text[],
  uploaded_by uuid,
  is_featured boolean DEFAULT false,
  download_count integer DEFAULT 0,
  view_count integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_resources_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_resources_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id),
  CONSTRAINT hackathon_resources_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_schedule_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  event_title text NOT NULL,
  event_description text,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['opening'::text, 'workshop'::text, 'mentorship'::text, 'meal'::text, 'activity'::text, 'judging'::text, 'closing'::text, 'other'::text])),
  start_time timestamp with time zone NOT NULL,
  end_time timestamp with time zone NOT NULL,
  location text,
  is_mandatory boolean DEFAULT false,
  max_participants integer,
  registered_count integer DEFAULT 0,
  meeting_link text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_schedule_events_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_schedule_events_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_sponsors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  sponsor_name text NOT NULL,
  sponsor_logo text,
  sponsor_website text,
  sponsor_tier text NOT NULL CHECK (sponsor_tier = ANY (ARRAY['title'::text, 'platinum'::text, 'gold'::text, 'silver'::text, 'bronze'::text, 'partner'::text])),
  contribution_amount numeric,
  contribution_type text CHECK (contribution_type = ANY (ARRAY['cash'::text, 'in-kind'::text, 'both'::text])),
  benefits_provided text,
  contact_person text,
  contact_email text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_sponsors_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_sponsors_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_submission_milestones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  submission_id integer NOT NULL,
  milestone_title text NOT NULL,
  milestone_description text,
  completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_submission_milestones_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_submission_milestones_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.hackathon_submissions(id)
);
CREATE TABLE public.hackathon_submissions (
  id integer NOT NULL DEFAULT nextval('hackathon_submissions_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  team_id integer,
  user_id text NOT NULL,
  project_name text NOT NULL,
  tagline text,
  description text NOT NULL,
  track text,
  github_repo text,
  demo_url text,
  video_url text,
  presentation_url text,
  cover_image text,
  additional_files ARRAY,
  technologies_used ARRAY,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'judging'::text, 'winner'::text, 'disqualified'::text])),
  submitted_at timestamp with time zone,
  score numeric,
  feedback text,
  prize_won text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  winner_position integer,
  winner_prize text,
  winner_announced_at timestamp with time zone,
  project_logo text,
  slug text UNIQUE,
  criteria_scores jsonb,
  gallery_images ARRAY DEFAULT '{}'::text[],
  CONSTRAINT hackathon_submissions_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_submissions_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_submissions_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id)
);
CREATE TABLE public.hackathon_team_invitations (
  id integer NOT NULL DEFAULT nextval('hackathon_team_invitations_id_seq'::regclass),
  team_id integer NOT NULL,
  hackathon_id integer NOT NULL,
  invited_by_user_id text NOT NULL,
  invited_user_id text,
  invited_email text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'declined'::text, 'expired'::text])),
  expires_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  responded_at timestamp with time zone,
  invite_token text UNIQUE,
  CONSTRAINT hackathon_team_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_team_invitations_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_team_invitations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id)
);
CREATE TABLE public.hackathon_team_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id integer NOT NULL,
  sender_id uuid,
  message text NOT NULL,
  message_type text DEFAULT 'text'::text CHECK (message_type = ANY (ARRAY['text'::text, 'file'::text, 'link'::text, 'code'::text])),
  attachments jsonb DEFAULT '[]'::jsonb,
  is_pinned boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_team_messages_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_team_messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES auth.users(id),
  CONSTRAINT hackathon_team_messages_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id)
);
CREATE TABLE public.hackathon_team_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id integer NOT NULL,
  task_title text NOT NULL,
  task_description text,
  assigned_to uuid,
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'urgent'::text])),
  status text NOT NULL DEFAULT 'todo'::text CHECK (status = ANY (ARRAY['todo'::text, 'in-progress'::text, 'review'::text, 'done'::text])),
  due_date timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_team_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_team_tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT hackathon_team_tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT hackathon_team_tasks_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id)
);
CREATE TABLE public.hackathon_teams (
  id integer NOT NULL DEFAULT nextval('hackathon_teams_id_seq'::regclass),
  hackathon_id integer NOT NULL,
  team_name text NOT NULL,
  team_code text NOT NULL UNIQUE,
  team_leader_id text NOT NULL,
  project_name text,
  project_description text,
  project_track text,
  github_repo text,
  demo_url text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'disbanded'::text, 'disqualified'::text])),
  is_complete boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT hackathon_teams_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_teams_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.hackathon_tracks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  track_name text NOT NULL,
  track_description text,
  track_icon text,
  prize_pool text,
  sponsor_id uuid,
  max_submissions integer,
  current_submissions integer DEFAULT 0,
  judging_criteria jsonb,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hackathon_tracks_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_tracks_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_tracks_sponsor_id_fkey FOREIGN KEY (sponsor_id) REFERENCES public.hackathon_sponsors(id)
);
CREATE TABLE public.hackathon_winners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  submission_id integer NOT NULL,
  team_id integer,
  user_id uuid NOT NULL,
  position integer NOT NULL CHECK ("position" > 0),
  prize_name text NOT NULL,
  prize_amount text,
  announced_at timestamp with time zone NOT NULL DEFAULT now(),
  announced_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  prize_position character varying,
  CONSTRAINT hackathon_winners_pkey PRIMARY KEY (id),
  CONSTRAINT hackathon_winners_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES auth.users(id),
  CONSTRAINT hackathon_winners_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT hackathon_winners_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.hackathon_submissions(id),
  CONSTRAINT hackathon_winners_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id),
  CONSTRAINT hackathon_winners_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT hackathon_winners_announced_by_fkey FOREIGN KEY (announced_by) REFERENCES auth.users(id)
);
CREATE TABLE public.hackathons (
  id integer NOT NULL DEFAULT nextval('hackathons_id_seq'::regclass),
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  subtitle text,
  tagline text NOT NULL,
  badge_text text,
  description text NOT NULL,
  registration_url text,
  cover_image text,
  start_date text NOT NULL,
  end_date text NOT NULL,
  duration text NOT NULL,
  format text NOT NULL,
  team_size text NOT NULL,
  judging_type text NOT NULL,
  results_date text NOT NULL,
  what_it_is text NOT NULL,
  the_idea text NOT NULL,
  who_joins jsonb NOT NULL,
  tech_rules jsonb NOT NULL,
  fun_awards jsonb NOT NULL,
  perks jsonb NOT NULL,
  cash_pool text,
  prize_pool jsonb,
  judging_description text NOT NULL,
  judging_criteria text NOT NULL,
  required_submissions jsonb NOT NULL,
  optional_submissions jsonb,
  announcements text,
  event_highlights text,
  sponsor_message text,
  faq_content text,
  timeline_details text,
  special_instructions text,
  theme_config jsonb,
  theme_color_primary text NOT NULL,
  theme_color_secondary text NOT NULL,
  theme_color_accent text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  location text,
  status text,
  focus_areas jsonb,
  devpost_url text,
  devpost_register_url text,
  sort_order integer,
  CONSTRAINT hackathons_pkey PRIMARY KEY (id)
);
CREATE TABLE public.judge_scores (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  judge_id uuid NOT NULL,
  submission_id integer NOT NULL,
  score numeric NOT NULL CHECK (score >= 0::numeric AND score <= 10::numeric),
  notes text,
  scored_at timestamp with time zone DEFAULT now(),
  CONSTRAINT judge_scores_pkey PRIMARY KEY (id),
  CONSTRAINT judge_scores_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT judge_scores_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES public.hackathon_judges(id),
  CONSTRAINT judge_scores_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.hackathon_submissions(id)
);
CREATE TABLE public.judge_scoring_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hackathon_id integer NOT NULL,
  judge_id uuid NOT NULL UNIQUE,
  token text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  last_accessed_at timestamp with time zone,
  CONSTRAINT judge_scoring_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT judge_scoring_tokens_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id),
  CONSTRAINT judge_scoring_tokens_judge_id_fkey FOREIGN KEY (judge_id) REFERENCES public.hackathon_judges(id)
);
CREATE TABLE public.moderation_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_type text NOT NULL CHECK (item_type = ANY (ARRAY['hackathon'::text, 'user'::text, 'project'::text, 'report'::text])),
  priority integer NOT NULL DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  title text NOT NULL,
  description text,
  target_type text NOT NULL,
  target_id text NOT NULL,
  target_data jsonb,
  report_count integer DEFAULT 1,
  reporter_ids ARRAY DEFAULT '{}'::uuid[],
  claimed_by uuid,
  claimed_at timestamp with time zone,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'claimed'::text, 'resolved'::text, 'dismissed'::text])),
  resolution text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT moderation_queue_pkey PRIMARY KEY (id),
  CONSTRAINT moderation_queue_claimed_by_fkey FOREIGN KEY (claimed_by) REFERENCES auth.users(id),
  CONSTRAINT moderation_queue_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.notification_reads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL,
  user_id uuid NOT NULL,
  read_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_reads_pkey PRIMARY KEY (id),
  CONSTRAINT notification_reads_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.notifications(id),
  CONSTRAINT notification_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.notification_targets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  notification_template_id uuid NOT NULL,
  target_type text NOT NULL CHECK (target_type = ANY (ARRAY['all_users'::text, 'specific_user'::text, 'organizers'::text, 'judges'::text, 'judge_tier'::text, 'hackathon_participants'::text, 'hackathon_teams'::text, 'hackathon_organizers'::text, 'role_based'::text, 'custom_filter'::text])),
  target_filter jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_targets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'info'::text CHECK (type = ANY (ARRAY['info'::text, 'success'::text, 'alert'::text, 'warning'::text, 'error'::text, 'task'::text, 'admin'::text, 'judge'::text, 'organizer'::text, 'system'::text, 'hackathon'::text, 'team'::text, 'submission'::text, 'announcement'::text])),
  icon text,
  action_url text,
  action_text text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone,
  is_deleted boolean NOT NULL DEFAULT false,
  scheduled_for timestamp with time zone,
  dedupe_key text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organizer_applications (
  id integer NOT NULL DEFAULT nextval('organizer_applications_id_seq'::regclass),
  user_id uuid,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  organization_name text,
  organization_type text CHECK (organization_type = ANY (ARRAY['individual'::text, 'student_club'::text, 'company'::text, 'nonprofit'::text, 'community'::text])),
  organization_website text,
  phone text,
  location text NOT NULL,
  previous_organizing_experience text NOT NULL,
  why_maximally text NOT NULL,
  linkedin text,
  twitter text,
  instagram text,
  additional_info text,
  agreed_to_terms boolean NOT NULL DEFAULT false,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'under_review'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizer_applications_pkey PRIMARY KEY (id),
  CONSTRAINT organizer_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT organizer_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.organizer_hackathons (
  id integer NOT NULL DEFAULT nextval('organizer_hackathons_id_seq'::regclass),
  organizer_id text NOT NULL,
  organizer_email text NOT NULL,
  hackathon_name text NOT NULL,
  slug text NOT NULL UNIQUE,
  tagline text,
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  format text NOT NULL CHECK (format = ANY (ARRAY['online'::text, 'offline'::text, 'hybrid'::text])),
  venue text,
  registration_deadline timestamp with time zone,
  duration text,
  eligibility ARRAY DEFAULT ARRAY[]::text[],
  team_size_min integer DEFAULT 1,
  team_size_max integer DEFAULT 4,
  registration_fee integer DEFAULT 0,
  max_participants integer,
  expected_participants integer,
  communication_channel text,
  communication_link text,
  tracks text DEFAULT '[]'::text,
  open_innovation boolean DEFAULT false,
  total_prize_pool text,
  prize_breakdown text DEFAULT '[]'::text,
  perks ARRAY DEFAULT ARRAY[]::text[],
  judging_criteria text DEFAULT '[]'::text,
  judges_mentors text DEFAULT '[]'::text,
  discord_link text,
  whatsapp_link text,
  website_url text,
  submission_platform text DEFAULT 'maximally'::text,
  submission_platform_link text,
  contact_email text,
  key_rules text,
  code_of_conduct text,
  promo_video_link text,
  gallery_images ARRAY DEFAULT ARRAY[]::text[],
  cover_image text,
  featured_badge boolean DEFAULT false,
  verification_docs ARRAY DEFAULT ARRAY[]::text[],
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'pending_review'::text, 'published'::text, 'rejected'::text, 'ended'::text, 'unpublished'::text])),
  publish_requested_at timestamp with time zone,
  reviewed_at timestamp with time zone,
  reviewed_by text,
  rejection_reason text,
  admin_notes text,
  views_count integer DEFAULT 0,
  registrations_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  rules_content text,
  eligibility_criteria text,
  submission_guidelines text,
  judging_process text,
  themes ARRAY DEFAULT ARRAY[]::text[],
  sponsors ARRAY DEFAULT ARRAY[]::text[],
  partners ARRAY DEFAULT ARRAY[]::text[],
  faqs text DEFAULT '[]'::text,
  require_approval boolean DEFAULT false,
  allow_team_changes boolean DEFAULT true,
  show_participant_count boolean DEFAULT true,
  submission_opens_at timestamp with time zone,
  submission_closes_at timestamp with time zone,
  results_announced_at timestamp with time zone,
  hackathon_status text DEFAULT 'draft'::text CHECK (hackathon_status = ANY (ARRAY['draft'::text, 'live'::text, 'ended'::text])),
  hackathon_logo text,
  winners_announced boolean DEFAULT false,
  winners_announced_at timestamp with time zone,
  banner_image text,
  primary_color text DEFAULT '#8B5CF6'::text,
  secondary_color text DEFAULT '#EC4899'::text,
  accent_color text DEFAULT '#06B6D4'::text,
  font_style text DEFAULT 'default'::text CHECK (font_style IS NULL OR (font_style = ANY (ARRAY['default'::text, 'modern'::text, 'retro'::text, 'minimal'::text]))),
  domains ARRAY DEFAULT '{}'::text[],
  gallery_published_at timestamp with time zone,
  is_featured boolean DEFAULT false,
  internal_notes text,
  unpublished_at timestamp with time zone,
  unpublished_by uuid,
  unpublish_reason text,
  gallery_public boolean DEFAULT false,
  auto_publish_gallery boolean DEFAULT false,
  CONSTRAINT organizer_hackathons_pkey PRIMARY KEY (id),
  CONSTRAINT organizer_hackathons_unpublished_by_fkey FOREIGN KEY (unpublished_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organizer_message_recipients (
  id integer NOT NULL DEFAULT nextval('organizer_message_recipients_id_seq'::regclass),
  message_id integer,
  organizer_user_id uuid,
  organizer_username text NOT NULL,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  replied boolean DEFAULT false,
  replied_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organizer_message_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT organizer_message_recipients_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.organizer_messages(id),
  CONSTRAINT organizer_message_recipients_organizer_user_id_fkey FOREIGN KEY (organizer_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.organizer_messages (
  id integer NOT NULL DEFAULT nextval('organizer_messages_id_seq'::regclass),
  subject text NOT NULL,
  content text NOT NULL,
  recipient_type text NOT NULL DEFAULT 'all'::text CHECK (recipient_type = ANY (ARRAY['all'::text, 'specific'::text, 'tier'::text, 'location'::text])),
  recipient_filter jsonb,
  recipient_count integer DEFAULT 0,
  sent_by uuid,
  sent_by_name text,
  sent_by_email text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'scheduled'::text])),
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sent_at timestamp with time zone,
  scheduled_for timestamp with time zone,
  total_sent integer DEFAULT 0,
  total_read integer DEFAULT 0,
  total_replied integer DEFAULT 0,
  CONSTRAINT organizer_messages_pkey PRIMARY KEY (id),
  CONSTRAINT organizer_messages_sent_by_fkey FOREIGN KEY (sent_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organizer_profiles (
  id integer NOT NULL DEFAULT nextval('organizer_profiles_id_seq'::regclass),
  user_id text NOT NULL UNIQUE,
  display_name text,
  organization_name text,
  organization_type text CHECK (organization_type = ANY (ARRAY['individual'::text, 'student_club'::text, 'company'::text, 'nonprofit'::text, 'community'::text])),
  bio text,
  location text,
  website text,
  logo_url text,
  linkedin text,
  twitter text,
  instagram text,
  total_hackathons_hosted integer DEFAULT 0,
  total_participants_reached integer DEFAULT 0,
  total_prize_money_distributed text,
  verified_organizer boolean DEFAULT false,
  total_views integer DEFAULT 0,
  total_registrations integer DEFAULT 0,
  average_rating text,
  verification_status text DEFAULT 'unverified'::text CHECK (verification_status = ANY (ARRAY['unverified'::text, 'pending'::text, 'verified'::text])),
  verification_docs ARRAY DEFAULT ARRAY[]::text[],
  verified_at timestamp with time zone,
  verified_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  tier text DEFAULT 'starter'::text CHECK (tier = ANY (ARRAY['starter'::text, 'verified'::text, 'senior'::text, 'chief'::text, 'legacy'::text])),
  sort_order integer DEFAULT 0,
  is_published boolean DEFAULT false,
  headline text,
  short_bio text,
  primary_expertise ARRAY DEFAULT '{}'::text[],
  secondary_expertise ARRAY DEFAULT '{}'::text[],
  years_of_experience integer DEFAULT 0,
  languages_spoken ARRAY DEFAULT '{}'::text[],
  public_achievements text,
  github text,
  email text,
  phone text,
  CONSTRAINT organizer_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organizer_trust_scores (
  organizer_id text NOT NULL,
  score integer NOT NULL DEFAULT 50 CHECK (score >= 0 AND score <= 100),
  factors jsonb NOT NULL DEFAULT '{"violations": 0, "account_age_days": 0, "total_hackathons": 0, "total_participants": 0, "approved_hackathons": 0, "rejected_hackathons": 0}'::jsonb,
  is_flagged boolean DEFAULT false,
  flag_reason text,
  flagged_at timestamp with time zone,
  flagged_by uuid,
  last_calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT organizer_trust_scores_pkey PRIMARY KEY (organizer_id),
  CONSTRAINT organizer_trust_scores_flagged_by_fkey FOREIGN KEY (flagged_by) REFERENCES auth.users(id)
);
CREATE TABLE public.people (
  id integer NOT NULL DEFAULT nextval('people_id_seq'::regclass),
  name character varying NOT NULL,
  role_in_company character varying NOT NULL,
  company character varying,
  description text,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['advisors'::character varying, 'organizing_board'::character varying, 'developers'::character varying, 'alumni'::character varying]::text[])),
  linkedin_url text,
  twitter_url text,
  github_url text,
  website_url text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT people_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_notifications (
  id bigint NOT NULL DEFAULT nextval('platform_notifications_id_seq'::regclass),
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL DEFAULT 'info'::text,
  icon text,
  link_url text,
  link_text text,
  target_audience text NOT NULL DEFAULT 'all'::text,
  is_active boolean DEFAULT true,
  priority integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT platform_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT platform_notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  username text UNIQUE CHECK (username ~ '^[a-zA-Z0-9_-]{3,30}$'::text),
  full_name text,
  avatar_url text,
  bio text,
  location text,
  skills ARRAY,
  github_username text,
  linkedin_username text,
  twitter_username text,
  website_url text,
  role text NOT NULL DEFAULT 'user'::text CHECK (role = ANY (ARRAY['user'::text, 'admin'::text, 'organizer'::text])),
  is_verified boolean DEFAULT false,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  hackathons_participated integer DEFAULT 0,
  hackathons_won integer DEFAULT 0,
  projects_submitted integer DEFAULT 0,
  total_prize_money text,
  total_events_judged integer DEFAULT 0,
  total_teams_evaluated integer DEFAULT 0,
  total_mentorship_hours integer DEFAULT 0,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.recommended_tools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tool_name text NOT NULL,
  tool_description text,
  tool_url text NOT NULL,
  tool_logo text,
  category text NOT NULL CHECK (category = ANY (ARRAY['framework'::text, 'library'::text, 'database'::text, 'hosting'::text, 'design'::text, 'devops'::text, 'api'::text, 'testing'::text, 'other'::text])),
  related_technologies ARRAY DEFAULT '{}'::text[],
  popularity_score integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT recommended_tools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.signup_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  otp_hash text NOT NULL,
  password_encrypted text NOT NULL,
  name text,
  username text,
  expires_at timestamp with time zone NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT signup_otps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  metric_type text NOT NULL,
  metric_name text NOT NULL,
  value numeric NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT system_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.team_collaboration_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  teammate_id uuid NOT NULL,
  hackathon_id integer NOT NULL,
  team_id integer NOT NULL,
  team_name text NOT NULL,
  hackathon_name text NOT NULL,
  collaborated_at timestamp with time zone NOT NULL DEFAULT now(),
  team_role text,
  teammate_role text,
  project_name text,
  project_position text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT team_collaboration_history_pkey PRIMARY KEY (id),
  CONSTRAINT team_collaboration_history_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.hackathon_teams(id),
  CONSTRAINT team_collaboration_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT team_collaboration_history_teammate_id_fkey FOREIGN KEY (teammate_id) REFERENCES auth.users(id),
  CONSTRAINT team_collaboration_history_hackathon_id_fkey FOREIGN KEY (hackathon_id) REFERENCES public.organizer_hackathons(id)
);
CREATE TABLE public.template_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.template_category_relations (
  template_id uuid NOT NULL,
  category_id uuid NOT NULL,
  CONSTRAINT template_category_relations_pkey PRIMARY KEY (template_id, category_id),
  CONSTRAINT fk_template_relation FOREIGN KEY (template_id) REFERENCES public.certificate_templates(id),
  CONSTRAINT fk_category_relation FOREIGN KEY (category_id) REFERENCES public.template_categories(id)
);
CREATE TABLE public.template_elements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  element_type text NOT NULL CHECK (element_type = ANY (ARRAY['text'::text, 'placeholder'::text, 'image'::text, 'shape'::text, 'qr_code'::text])),
  content text,
  position_x integer NOT NULL,
  position_y integer NOT NULL,
  width integer NOT NULL,
  height integer NOT NULL,
  rotation integer DEFAULT 0,
  z_index integer DEFAULT 0,
  style_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_elements_pkey PRIMARY KEY (id),
  CONSTRAINT fk_template FOREIGN KEY (template_id) REFERENCES public.certificate_templates(id)
);
CREATE TABLE public.user_hackathon_preferences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  preferred_formats ARRAY DEFAULT '{}'::text[],
  preferred_domains ARRAY DEFAULT '{}'::text[],
  preferred_team_sizes ARRAY DEFAULT '{}'::text[],
  skill_level text CHECK (skill_level IS NULL OR (skill_level = ANY (ARRAY['beginner'::text, 'intermediate'::text, 'advanced'::text, 'any'::text]))),
  location_preference text CHECK (location_preference IS NULL OR (location_preference = ANY (ARRAY['online'::text, 'offline'::text, 'hybrid'::text, 'any'::text]))),
  notification_enabled boolean DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_hackathon_preferences_pkey PRIMARY KEY (id),
  CONSTRAINT user_hackathon_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_moderation_actions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['warning'::text, 'mute'::text, 'suspend'::text, 'ban'::text, 'unban'::text, 'unmute'::text, 'note'::text, 'verify'::text, 'unverify'::text])),
  reason text NOT NULL,
  duration_hours integer,
  expires_at timestamp with time zone,
  performed_by uuid NOT NULL,
  related_report_id uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_moderation_actions_pkey PRIMARY KEY (id),
  CONSTRAINT user_moderation_actions_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES auth.users(id),
  CONSTRAINT user_moderation_actions_related_report_id_fkey FOREIGN KEY (related_report_id) REFERENCES public.user_reports(id),
  CONSTRAINT user_moderation_actions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_moderation_status (
  user_id uuid NOT NULL,
  is_banned boolean DEFAULT false,
  is_muted boolean DEFAULT false,
  is_suspended boolean DEFAULT false,
  ban_reason text,
  mute_reason text,
  suspend_reason text,
  banned_at timestamp with time zone,
  muted_at timestamp with time zone,
  suspended_at timestamp with time zone,
  ban_expires_at timestamp with time zone,
  mute_expires_at timestamp with time zone,
  suspend_expires_at timestamp with time zone,
  warning_count integer DEFAULT 0,
  total_reports_received integer DEFAULT 0,
  last_warning_at timestamp with time zone,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_moderation_status_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_moderation_status_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_notification_reads (
  id bigint NOT NULL DEFAULT nextval('user_notification_reads_id_seq'::regclass),
  user_id uuid NOT NULL,
  notification_id bigint NOT NULL,
  read_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_notification_reads_pkey PRIMARY KEY (id),
  CONSTRAINT user_notification_reads_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_notification_reads_notification_id_fkey FOREIGN KEY (notification_id) REFERENCES public.platform_notifications(id)
);
CREATE TABLE public.user_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  reporter_id uuid NOT NULL,
  reported_user_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['harassment'::text, 'spam'::text, 'inappropriate_content'::text, 'impersonation'::text, 'cheating'::text, 'hate_speech'::text, 'scam'::text, 'other'::text])),
  description text NOT NULL,
  screenshot_urls ARRAY DEFAULT '{}'::text[],
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'under_review'::text, 'resolved'::text, 'dismissed'::text])),
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  admin_notes text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  resolution text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_reports_pkey PRIMARY KEY (id),
  CONSTRAINT user_reports_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id),
  CONSTRAINT user_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id),
  CONSTRAINT user_reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_trust_scores (
  user_id uuid NOT NULL,
  score integer NOT NULL DEFAULT 50 CHECK (score >= 0 AND score <= 100),
  factors jsonb NOT NULL DEFAULT '{"verified_email": false, "account_age_days": 0, "reports_received": 0, "moderation_actions": 0, "reports_filed_valid": 0, "successful_hackathons": 0}'::jsonb,
  last_calculated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_trust_scores_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_trust_scores_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);