-- Supabase Database Seeding Script for Maximally Hackathons
-- This script creates the hackathons table if it doesn't exist and seeds it with all hackathon data

-- Create the hackathons table (if it doesn't exist)
CREATE TABLE IF NOT EXISTS hackathons (
  id SERIAL PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  tagline TEXT NOT NULL,
  badge_text TEXT,
  description TEXT NOT NULL,
  registration_url TEXT,
  cover_image TEXT,
  start_date TEXT NOT NULL,
  end_date TEXT NOT NULL,
  duration TEXT NOT NULL,
  format TEXT NOT NULL,
  team_size TEXT NOT NULL,
  judging_type TEXT NOT NULL,
  results_date TEXT NOT NULL,
  what_it_is TEXT NOT NULL,
  the_idea TEXT NOT NULL,
  who_joins JSONB NOT NULL,
  tech_rules JSONB NOT NULL,
  fun_awards JSONB NOT NULL,
  perks JSONB NOT NULL,
  cash_pool TEXT,
  prize_pool JSONB,
  judging_description TEXT NOT NULL,
  judging_criteria TEXT NOT NULL,
  required_submissions JSONB NOT NULL,
  optional_submissions JSONB,
  announcements TEXT,
  event_highlights TEXT,
  sponsor_message TEXT,
  faq_content TEXT,
  timeline_details TEXT,
  special_instructions TEXT,
  theme_config JSONB,
  theme_color_primary TEXT NOT NULL,
  theme_color_secondary TEXT NOT NULL,
  theme_color_accent TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Clear existing data (optional - comment out if you want to keep existing data)
DELETE FROM hackathons;

-- Insert all hackathon data
INSERT INTO hackathons (
  slug, title, tagline, badge_text, description, registration_url,
  start_date, end_date, duration, format, team_size, judging_type, results_date,
  what_it_is, the_idea, who_joins, tech_rules, fun_awards, perks, cash_pool,
  prize_pool, judging_description, judging_criteria, required_submissions,
  optional_submissions, theme_color_primary, theme_color_secondary, theme_color_accent, is_active
) VALUES

-- Codepocalypse
('codepocalypse', 'Maximally Codepocalypse', 'What would you build if the internet had 48 hours left?', '48 HOUR CHAOS',
'A 48-hour chaotic hackathon where builders create in the face of digital apocalypse. Build like the end is near.',
'https://tally.so/r/wgJM6B', 'Oct 18, 2025', 'Oct 19, 2025', '48 hours', 'Online', 'Solo or up to 4',
'Async with optional pitch', 'Mid-November ceremony',
'A 48-hour hackathon themed around digital apocalypse. Build software like the internet has 48 hours left. Any stack, any idea, just ship it before the countdown ends.',
'In a world where technology is failing and systems are breaking down, what would you build in the final 48 hours? Create tools, games, or apps that embrace chaos and help humanity survive the digital apocalypse.',
'["Anyone, anywhere", "No age, no filters", "Teams up to 4 or solo", "Beginners welcome", "No-coders welcome", "Designers welcome", "Tinkerers welcome", "No prep, no pressure"]',
'["Any stack, any tool", "AI tools allowed", "No-code allowed", "Cursed workflows encouraged", "Plagiarism = disqualification", "Must include code or files", "Short readme required", "Optional 60s video"]',
'["Most cursed build", "Shouldn''t have worked but did", "Built while sleep-deprived", "Best bug that became a feature"]',
'["Join the chaos network", "Featured on Maximally platform", "Connect with fellow chaos builders", "Learn from breaking things"]',
'₹5000+ prizes',
'[{"title": "Winner", "amount": "₹3000", "description": "Best overall project"}, {"title": "Runner-up", "amount": "₹2000", "description": "Second place"}]',
'Projects judged on creativity, functionality, chaos factor, and apocalypse theme adherence.',
'Innovation in chaos (25%), Technical execution (25%), Theme adherence (25%), Overall impact (25%)',
'["Working demo or prototype", "Public repository with code", "Brief project description", "List of technologies used"]',
'["60-second demo video", "Deployment link if applicable", "Team member details"]',
'#dc2626', '#1f2937', '#fbbf24', true),

-- Protocol 404
('protocol-404', 'Protocol 404', 'Break the system. Build yours.', 'SYSTEM ERROR',
'A 48-hour hackathon for system-breakers. When the system fails, we build better ones.',
'https://tally.so/r/wgJM6B', 'Oct 4, 2025', 'Oct 5, 2025', '48 hours', 'Online', 'Solo or up to 4',
'Async submission review', 'October 12, 2025',
'Protocol 404 is for builders who see broken systems and think ''I can fix that.'' 48 hours to prototype your solution to something fundamentally broken.',
'Every system eventually breaks. When protocols fail, networks collapse, and error 404 becomes the norm - that''s when true builders shine. Build tools that work when everything else doesn''t.',
'["System breakers", "Protocol hackers", "Error hunters", "Chaos engineers", "Infrastructure rebels", "Network builders", "Anyone who''s seen a 404 and wanted to fix it"]',
'["Any stack allowed", "Open source encouraged", "AI tools permitted", "No-code solutions welcome", "Must solve a real problem", "Code repository required", "Brief documentation needed"]',
'["Most elegant failure handler", "Best system resurrection", "Chaos utility champion", "Protocol perfectionist"]',
'["Join the protocol network", "Featured on system builder showcases", "Connect with infrastructure hackers", "Learn advanced debugging techniques"]',
'₹5000+ in prizes',
'[{"title": "System Breaker", "amount": "₹3000", "description": "Best protocol solution"}, {"title": "Error Hunter", "amount": "₹2000", "description": "Best debugging tool"}]',
'Projects evaluated on problem-solving approach, technical innovation, and real-world applicability.',
'Problem identification (20%), Solution design (30%), Technical execution (30%), Impact potential (20%)',
'["Working prototype or demo", "Source code repository", "Problem statement and solution", "Technology stack documentation"]',
'["Demo video (max 2 minutes)", "Deployment/live demo link", "Future roadmap"]',
'#ef4444', '#000000', '#fbbf24', true),

-- Hacktober
('hacktober', 'Maximally Hacktober', 'Build slow. Build loud. Finish strong.', 'MONTH-LONG MADNESS',
'A month-long hackathon for builders who won''t quit. October 1-31, 2025. Deep work, loud launches.',
'https://tally.so/r/wgJM6B', 'Oct 1, 2025', 'Oct 31, 2025', '31 days', 'Online', 'Solo or up to 4',
'Final submission review', 'November 15, 2025',
'Hacktober is a month-long building marathon. Not a sprint hackathon, but a sustained effort to create something meaningful. Build consistently, document loudly, finish strong.',
'Most hackathons are weekend sprints. Hacktober is different - a full month to build something substantial. Take time to iterate, polish, and create something you''re truly proud of.',
'["Long-form builders", "Perfectionist makers", "Indie hackers", "Product builders", "Anyone with a big idea", "Teams wanting depth over speed", "Builders who love the process"]',
'["Any technology stack", "Open source preferred", "AI tools encouraged", "No-code solutions welcome", "Must show consistent progress", "Weekly check-ins required", "Final demo mandatory"]',
'["Most consistent builder", "Best documentation", "Biggest transformation", "Community favorite"]',
'["Monthly builder community access", "Featured on Maximally showcase", "Mentorship opportunities", "Product launch support"]',
'₹10,000+ prize pool',
'[{"title": "Master Builder", "amount": "₹5000", "description": "Best overall project"}, {"title": "Consistency Award", "amount": "₹3000", "description": "Most consistent progress"}, {"title": "Community Choice", "amount": "₹2000", "description": "Voted by community"}]',
'Projects judged on consistency, quality, innovation, and community impact over the month-long period.',
'Consistency (25%), Product quality (25%), Innovation (25%), Community engagement (25%)',
'["Complete working product", "Development log/journal", "Public repository", "Demo video (max 5 minutes)"]',
'["Live deployment link", "User testimonials", "Future development plans"]',
'#d97706', '#8b4513', '#f59e0b', true),

-- Steal-A-Thon
('steal-a-thon', 'Maximally Steal-A-Thon', 'Good artists copy. Great artists steal. Greatest artists improve.', 'ORIGINAL THEFT',
'24-hour hackathon where you upgrade existing projects. Find something cool, make it cooler.',
'https://tally.so/r/wgJM6B', 'Nov 9, 2025', 'Nov 10, 2025', '24 hours', 'Online', 'Solo or up to 4',
'Innovation on existing work', 'November 17, 2025',
'Steal-A-Thon celebrates the art of iteration. Find an existing open-source project, tool, or idea, then make it significantly better in 24 hours.',
'Innovation doesn''t always mean starting from scratch. Sometimes the best way forward is to take something good and make it great. Find, fork, and improve.',
'["Coders", "No-coders", "Designers", "First-timers", "Meme builders", "Indie hackers", "Chaos coders", "Anyone who believes good artists copy and great artists steal"]',
'["Base your work on a public project", "Transform it enough to be yours", "Include a link to the original", "Keep it SFW and non-harmful", "Lazy clones get disqualified"]',
'["Most creative theft", "Best transformation", "Funniest rename", "Should-be-official-fork"]',
'["Join the remix network", "Featured on improvement showcases", "Connect with iteration masters", "Learn advanced forking techniques"]',
'₹3000+ in prizes',
'[{"title": "Greatest Thief", "amount": "₹2000", "description": "Best improvement"}, {"title": "Creative Upgrade", "amount": "₹1000", "description": "Most creative transformation"}]',
'Projects judged on the creativity of improvements, technical execution, and how well they transform the original.',
'Improvement creativity (30%), Technical execution (25%), Originality in changes (25%), Overall polish (20%)',
'["Your improved version", "Link to original project", "List of improvements made", "Brief explanation of changes"]',
'["Before/after comparison video", "Pull request to original (if applicable)", "User feedback on improvements"]',
'#1f2937', '#374151', '#10b981', true),

-- Grand Tech Assembly
('grand-tech-assembly', 'Grand Tech Assembly', '7 days. 4 tracks. 1 legendary build.', 'GTA SEASON',
'Week-long hackathon with mission tracks. Choose your path: Heist, Street Hustle, Vigilante, or Mastermind.',
'https://tally.so/r/wgJM6B', 'Nov 1, 2025', 'Nov 7, 2025', '7 days', 'Online, Devpost submissions', 'Solo or up to 4',
'Track-based judging', 'November 14, 2025',
'Grand Tech Assembly is a week-long hackathon with GTA-themed mission tracks. Choose your criminal path and build your way to the top of the leaderboard.',
'Every great heist needs a plan, every street hustle needs grit, every vigilante needs justice, and every mastermind needs strategy. Pick your track and build something legendary.',
'["Anyone anywhere", "Beginners and no-coders", "Designers", "Hackers", "Indie makers", "No prep needed", "Any stack works"]',
'["Choose one primary mission track", "Side missions are bonus points", "Any technology allowed", "AI tools permitted", "Must relate to chosen track theme", "Code repository required", "Devpost submission mandatory"]',
'["Best heist automation", "Most profitable hustle", "Justice served award", "Criminal mastermind", "Cross-track excellence"]',
'["Join the GTA network", "Featured on criminal showcases", "Access to mission briefings", "Connect with track leaders"]',
'₹8000+ across all tracks',
'[{"title": "Track Champion", "amount": "₹2000", "description": "Best in each track"}, {"title": "Cross-Track Master", "amount": "₹2000", "description": "Multi-track excellence"}]',
'Projects judged within their chosen track category, with bonus points for cross-track innovation and overall execution quality.',
'Track alignment (25%), Innovation (25%), Technical execution (25%), Presentation (25%)',
'["Devpost project submission", "Working demo or prototype", "Mission track selection", "Source code repository"]',
'["Demo video (max 60 seconds)", "Side mission completions", "Team introduction"]',
'#059669', '#1f2937', '#fbbf24', true),

-- PromptStorm
('prompt-storm', 'Maximally PromptStorm', '24 hours. Infinite prompts. Pure AI creativity.', 'AI POWERED',
'24-hour AI-focused hackathon. Build anything where prompts are the core technology. ChatGPT, Claude, Midjourney - go wild.',
'https://tally.so/r/wgJM6B', 'Oct 25, 2025', 'Oct 26, 2025', '24 hours', 'Online', 'Solo or up to 4',
'AI innovation and prompt creativity', 'November 2, 2025',
'PromptStorm is all about AI creativity. Build tools, art, stories, games, or anything where prompt engineering is the main technology. Show us what happens when humans and AI collaborate.',
'We''re in the prompt era. The best builders aren''t necessarily the best coders - they''re the best prompt engineers. Show us what''s possible when prompts become your primary tool.',
'["AI tinkerers", "Writers", "Designers", "Coders", "No-coders", "Beginners who want a simple way to compete"]',
'["Prompts must be central to the build", "Keep it SFW and non-harmful", "Team work is allowed, outside assets must be credited", "Share prompt logs or representative prompts"]',
'["Most creative prompt use", "Best AI collaboration", "Prompt engineering master", "Unexpected AI application"]',
'["Join the AI builder community", "Featured on prompt showcases", "Access to prompt libraries", "Connect with AI innovators"]',
'₹4000+ in AI prizes',
'[{"title": "Prompt Master", "amount": "₹2500", "description": "Best prompt engineering"}, {"title": "AI Innovator", "amount": "₹1500", "description": "Most creative AI use"}]',
'Projects evaluated on prompt creativity, AI integration quality, innovation in human-AI collaboration, and overall execution.',
'Prompt innovation (30%), AI integration (25%), Creativity (25%), Execution (20%)',
'["Working AI-powered project", "Key prompts used (sanitized)", "Brief explanation of AI role", "Technology and AI tools list"]',
'["Demo video showing AI interaction", "Prompt engineering insights", "Future AI integration plans"]',
'#3b82f6', '#1e40af', '#60a5fa', true),

-- Code Hypothesis
('codehypothesis', 'Code Hypothesis', 'A 24-hour hackathon for wild ideas', 'GRAND INDIAN HACKATHON',
'Test theories instead of pitching. Part of Maximally Grand Indian Hackathon Season. Where code meets graffiti.',
'https://codehypothesis.devpost.com/', 'Sept 28, 2025', 'Sept 28, 2025', '24 hours', 'Online', 'Solo or teams',
'Async submission review', 'Mid November',
'Not your average hackathon. Instead of pitching polished ideas, you test theories and challenge assumptions. This is about raw experimentation, fast prototyping, and proving (or disproving) your wildest coding hypotheses in just 24 hours.',
'Code Hypothesis is where theory meets reality. Build prototypes to test your coding assumptions, challenge conventional wisdom, and prove wild theories through raw experimentation.',
'["Builders with weird ideas", "Absolute beginners", "No-code rebels", "Students & dropouts", "Indie hackers", "Theory breakers"]',
'["Any stack, any tool", "Test a coding hypothesis", "Must include working prototype", "Code repository required", "Brief documentation needed", "Raw experimentation encouraged"]',
'["Most mind-bending hypothesis", "Best theory destroyer", "Wildest assumption challenge", "Creative rebellion award"]',
'["Join the hypothesis network", "Featured on theory showcases", "Connect with experimental builders", "Learn breakthrough thinking"]',
'₹5000+ in prizes',
'[{"title": "Hypothesis Master", "amount": "₹3000", "description": "Best theory test"}, {"title": "Reality Breaker", "amount": "₹2000", "description": "Most surprising result"}]',
'Projects judged on hypothesis creativity, experimental approach, technical execution, and insights gained from testing theories.',
'Hypothesis originality (30%), Experimental approach (25%), Technical execution (25%), Insights gained (20%)',
'["Working prototype or demo", "Hypothesis statement", "Test results and findings", "Source code repository"]',
'["Demo video", "Experimental process documentation", "Future research directions"]',
'#10b981', '#000000', '#fbbf24', true),

-- Project CodeGen
('project-codegen', 'Project CodeGen', 'Build like you''re 6. Ship like you''re 16.', 'PLAYFUL HACKATHON',
'A 48-hour hackathon for builders who play. Not about disruption or MVPs. It''s about play. Drop the pitch decks, pick up crayons.',
'https://projectcodegen.devpost.com', 'Oct 11, 2025', 'Oct 12, 2025', '48 hours', 'Online', 'Solo or teams (max 4)',
'Async judging, no live pitch', 'Before Nov ceremony',
'Not about disruption or MVPs. It''s about play. Drop the pitch decks, pick up crayons. Build like a kid — silly ideas, joyful logic, weird prototypes. Make tech fun again.',
'Project CodeGen celebrates the joy of building. Inspired by notebooks, toys, science fairs, Lego builds, and Scratch projects. You''re building for your younger self.',
'["Teen builders", "First-timers", "Designers + no-coders", "Scratch veterans", "Makers who like color, fun, and zero stress"]',
'["48-hour online event", "Solo or teams (max 4)", "Open to all ages, worldwide", "Any stack or tool", "No prep, no live calls", "Serious design allowed, serious tone not allowed", "You''re building for your younger self"]',
'["Most playful build", "Best imagination", "Highest joy factor", "Most useful in disguise"]',
'["Join the playful builder community", "Featured on creativity showcases", "Connect with joyful makers", "Rediscover the fun in coding"]',
'₹5000+ in prizes',
'[{"title": "Big Kid Award", "amount": "₹3000", "description": "Best overall playful project + LOR + feature"}, {"title": "Most Playful Build", "amount": "₹2000", "description": "Highest creativity and joy"}]',
'Projects evaluated on imagination, execution, usefulness in disguise, presentation, and joy factor.',
'Imagination (30%), Execution (25%), Usefulness in Disguise (20%), Presentation (15%), Joy Factor (10%)',
'["Prototype link (GitHub, Notion, Figma, no-code, etc.)", "Write-up: what you built, why it''s playful, hidden smartness", "Working playful project"]',
'["1-min silly demo video", "Process documentation", "Fun screenshots or demos"]',
'#f59e0b', '#ec4899', '#3b82f6', true);

-- Update the timestamps
UPDATE hackathons SET updated_at = NOW() WHERE id IS NOT NULL;

-- Verify the data was inserted
SELECT COUNT(*) as total_hackathons FROM hackathons;
SELECT slug, title, is_active FROM hackathons ORDER BY created_at;